### ISSUE TITLE
Can I integrate it with Angular

### ISSUE THREAD

**Issue by tuminzee** [xyfir/rword#6]
I tried to integrate it with my angular code, but I failed. 
I think the package is for nodejs, or am I wrong. 

Sorry if this issue looks silly.  Can you please guide me with if there is way to integrate it with angular.

**Comment by MrXyfir** [comment]
Correct, it is only meant for Node.js.

My advice would be to create an API route on your server to generate words.

You could fork it and rework it to run on the client but I wouldn't recommend it since the word lists are  large and would make your app too big!

**Comment by tuminzee** [comment]
Thank you so much for responding. 
I was going to make an api, but I found one online so I  didn't try it. 
https://random-words-api.vercel.app/word
